version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "01:17"
      timezone: Asia/Singapore
    open-pull-requests-limit: 5
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "01:47"
      timezone: Asia/Singapore
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: ci
